Traceback (most recent call last):
  File "./bot.py", line 2, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "./bot.py", line 2, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
